# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9a7a5273a679f78abdc332c90bd2fda6df5e3846d2df66c4a38f5e94a33d2a27c6ad1dd892096d6333a65ee95c555fc6a125aa7f3797d8384203b179522f782d

test:
  secret_key_base: 3e9c6eb3e4a3c46ced8d7d3c9537d6301c6d17ee4d66a66759da3c6938934c884d885f212e9e2bbb6af621be1eff27230b24af6094080a0cc6967d9c657216ec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
